spring.application.name=GestaoAcademica
server.port=8080
app.csv.usuarios-file=data/usuarios.csv
app.csv.atividades-file=data/atividades.csv
app.csv.submissoes-file=data/submissoes.csv
app.storage.upload-dir=data/uploads
app.csv.notificacoes-file=data/notificacoes.csv
app.csv.turmas-file=data/turmas.csv
app.csv.topicos-file=data/topicos.csv
app.csv.mensagens-file=data/mensagens.csv
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
