spring.application.name=GestaoAcademica
server.port=8080
app.csv.usuarios-file=data/usuarios.csv
app.csv.atividades-file=data/atividades.csv
app.csv.submissoes-file=data/submissoes.csv
app.storage.upload-dir=data/uploads
